### ISSUE TITLE
transient.cursor move commands don't work in mark mode

### ISSUE THREAD

**Issue by mtalexan** [yasuyuky/transient-emacs#170] opened 2020-04-15 21:02 UTC
After setting the mark with transient.setMark bound to a keypress, only the arrow keys work to expand the selected area.  The non-arrow keys that are bound to the transient.cursorLeft, transient.cursorRight, transient.cursorUp, and transient.cursorDown terminate the mark.
Using VSCode, this is 100% reproducible.

Steps to Reproduce
1. Open some file with text/content
2. Ctrl+Space to set mark
3. Use RightArrow a few times to expand the selected area and make it visible
4. Press Ctrl+F, which triggers transient.cursorRight and should be identical to the RightArrow
5. Notice the selection immediately ended
6. Assuming a read/write buffer, press Ctrl+W
7. Confirm it also didn't do a "cut" in what used to be selection, confirming it's not just a display issue

I noticed with some of the other VSCode extensions that try to do this same thing, they frequently had to define an `inRegionMode` flag and use `cursorSelectRight`, `cursorSelectLeft`, `cursorSelectUp`, `cursorSelectDown` rather than just `cursorRight`, `cursorLeft`, `cursorUp`, `cursorDown` during Region selection mode.

**Comment by yasuyuky** [comment] 2020-04-21 04:40
Thank you very much for the report.
Since I couldn't reproduce it here for a moment, can you give me more details on the environment?
What are your OS and version?
Please also make sure that Ctrl+F does not have any other keybindings assigned to it.

**Comment by yasuyuky** [comment] 2020-05-11 14:12
This issue seems to be stale, so I close it once.
If you have any further information, please feel free to reopen.

**Closed by yasuyuky** 2020-05-11 14:12 UTC
